import { StyleSheet } from 'react-native';

// --- StyleSheet for React Native Components ---
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f3f4f6',
    padding: 16,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#1f2937',
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 16,
    textAlign: 'center',
    color: '#4b5563',
    marginBottom: 24,
  },
  inputSection: {
    marginBottom: 24,
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#1f2937',
    backgroundColor: '#fff',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 16,
  },
  parentsContainer: {
    flexDirection: 'column',
    gap: 16,
  },
  parentCard: {
    backgroundColor: '#eff6ff',
    padding: 16,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  leaveEndText: {
    marginTop: 8,
    fontSize: 12,
    color: '#4b5563',
  },
  otherCaregiversContainer: {
    gap: 16,
  },
  otherCaregiverCard: {
    backgroundColor: '#f5f3ff',
    padding: 16,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  addButton: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#22c55e',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    alignSelf: 'flex-start',
  },
  addButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  removeButton: {
    marginLeft: 16,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: '#ef4444',
    borderRadius: 8,
  },
  removeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  outputSection: {
    backgroundColor: '#f9fafb',
    padding: 16,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    marginTop: 24,
  },
  tableScrollView: {},
  tableHeaderRowsContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#e5e7eb',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: '#e5e7eb',
  },
  subHeaderRow: {
    flexDirection: 'row',
  },
  tableHeaderCell: {
    width: 80,
    textAlign: 'center',
    fontSize: 10,
    fontWeight: 'bold',
    color: '#6b7280',
    textTransform: 'uppercase',
    paddingHorizontal: 4,
  },
  dateHeader: {
    fontWeight: 'normal',
    fontSize: 9,
    color: '#4b5563',
  },
  personHeader: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: 120,
    height: '100%',
    textAlignVertical: 'bottom',
    paddingBottom: 10,
    backgroundColor: '#e5e7eb',
    zIndex: 2,
  },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'center',
  },
  tableCell: {
    width: 80,
    paddingVertical: 10,
    paddingHorizontal: 4,
    textAlign: 'center',
    fontSize: 14,
    color: '#4b5563',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stickyCell: {
    width: 120,
    textAlign: 'left',
    fontWeight: 'bold',
    color: '#1f2937',
    backgroundColor: '#fff',
    zIndex: 1,
  },
  personNameCell: {
    fontSize: 14,
    fontWeight: '500',
  },
  parentCoveredCell: {
    backgroundColor: '#dcfce7',
  },
  parentNotCoveredCell: {
    backgroundColor: '#fee2e2',
  },
  otherCoveredCell: {
    backgroundColor: '#ede9fe',
  },
  otherNotCoveredCell: {
    backgroundColor: '#f3f4f6',
  },
  tableFooterRow: {
    flexDirection: 'row',
    backgroundColor: '#e5e7eb',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderColor: '#e5e7eb',
  },
  summaryCell: {
    fontWeight: 'bold',
    fontSize: 14,
  },
  summaryCovered: {
    backgroundColor: '#d1fae5',
    color: '#065f46',
  },
  summaryNotCovered: {
    backgroundColor: '#fecaca',
    color: '#991b1b',
  },
  coverageStatusSuccess: {
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
    backgroundColor: '#d1fae5',
  },
  coverageStatusWarning: {
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
    backgroundColor: '#fef3c7',
  },
  coverageStatusText: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '500',
  }
});

export default styles;